export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import '../../tailwind.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='h-screen w-screen'>{children}</body>
    </html>
  )
}
